<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>Home</li>
                    <li>Store</li>
                    <li>Game</li>
                </ul>
            </nav>
        </header>    
    </body>
</html>